-- Supabase Database Schema for Posture Coach
-- You can run this in your Supabase SQL Editor to create the necessary tables.

-- 1. Create the Users table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT,
  age INTEGER,
  fitness_level TEXT,
  goals TEXT,
  injuries TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Create the Sessions (Workouts) table
CREATE TABLE IF NOT EXISTS public.sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  exercise TEXT NOT NULL,
  exercise_name TEXT NOT NULL,
  reps INTEGER DEFAULT 0,
  good_reps INTEGER DEFAULT 0,
  bad_reps INTEGER DEFAULT 0,
  form_score INTEGER DEFAULT 0,
  rep_history TEXT,
  duration_secs INTEGER DEFAULT 0,
  plank_hold_secs INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Optional: Add Row Level Security (RLS) policies if you plan to access Supabase directly from the frontend later
-- (Currently, your Node.js backend handles the database inserts securely)
-- ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
